title: Glitched Classics Collection
author: Mothership 
email: 
description: >-
  1 of 1 dollection of art inspired by public domain masterpieces

social:
  twitter: 
  facebook: 
  instagram: 
  github: joaomlneto
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
